import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { getAuth, signInWithEmailAndPassword } from "firebase/auth";
import app from "@/config/firebaseConfig";
import Router from "next/router";

export default function SignIn() {
  const auth = getAuth(app);

  const handleSignIn = () => {
    signInWithEmailAndPassword(auth, "blake@test.com", "Test1234*")
      .then((userCredential) => {
        Router.push("/dashboard");
      })
      .catch((error) => {
        console.log("error: ", error);
      });
  };

  return (
    <>
      <Head>
        <title>Sign In</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h3 style={{ marginBottom: "10px" }}>Sign In</h3>
        <div style={{ display: "flex", flexDirection: "column" }}>
          <input placeholder="email" style={{ marginBottom: "10px" }} />
          <input placeholder="password" style={{ marginBottom: "10px" }} />
          <button
            style={{ marginBottom: "10px" }}
            onClick={() => handleSignIn()}
          >
            Sign In
          </button>
        </div>
      </main>
    </>
  );
}
