import { GetServerSidePropsContext } from "next";
import Head from "next/head";
import nookies from "nookies";
import { firebaseAdmin } from "@/config/firebaseAdmin";

// Going to the root route "/" will check for:
// Is the user authenticated? Goto Dashboard
// Is the user not authenticated? Goto Sign In page

export default function Home() {
  return (
    <>
      <Head>
        <title>Trust Poll</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
}

export async function getServerSideProps(context: GetServerSidePropsContext) {
  try {
    const cookies = nookies.get(context);
    await firebaseAdmin.auth().verifyIdToken(cookies.token);

    return {
      props: { message: "Verified token" },
      redirect: {
        destination: "/dashboard",
        permanent: false,
      },
    };
  } catch (error) {
    console.log("error: ", error);
    return {
      props: {},
      redirect: {
        destination: "/sign_in",
        permanent: false,
      },
    };
  }
}
